### ISSUE TITLE
Track Maintainer/Track Mentor

### ISSUE THREAD

**Issue by kotp** [exercism/xpascal#25]
Please add me to this track, would like to get it up and in shape.

@kytrinyx

**Comment by rpottsoh** [comment]
Victor, 

Thanks for your willingness to help.  I've PR'd 11 exercises but further development of this track has stalled.  I'm not sure what the next steps ought to be.

Thanks,

Ryan 

Sent from my android device.

**Comment by kotp** [comment]
Yes, I noticed that for sure.  It is why I am wanting access to the track more formally.

**Comment by kytrinyx** [comment]
Thanks @kotp! I realized we don't have a team for it yet, I'll create that and add both of you to it.

**Comment by kytrinyx** [comment]
Ok, done! I've added you both as track mentors to the track as well.

**Comment by kotp** [comment]
Looks like no rights to write bit on this repository for me.

**Comment by rpottsoh** [comment]
No write bit for me too....
